databases:
  - name: devops-db
    plan: free
    databaseName: devopsdb
    user: devops

services:
  - type: web
    name: auto-scaling-web-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devops-db
          property: connectionString
